version: '2'

services:
  todo:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: todo
    volumes:
      - ./src:/app/src
    expose:
      - 9001
    ports: 
      - 9001:9001
    networks:
      todo-network:
        aliases:
          - todo
  mongo:
    image: mongo
    ports: 
      - 9002:27017
    volumes: 
      - ../db-data:/data/db
    networks:
      todo-network:
        aliases:
          - mongo

networks:
  todo-network:
    external:
        name: todo-network